(() => {
  const orders = () => { try { const o = JSON.parse(localStorage.getItem('nexora-last-order') || 'null'); return o ? [o] : []; } catch { return []; } };
  const getUser = () => { try { return JSON.parse(localStorage.getItem('nexora-user') || 'null'); } catch { return null; } };
  const setUser = (u) => localStorage.setItem('nexora-user', JSON.stringify(u));
  const close = () => document.querySelector('.account-modal-backdrop')?.remove() || document.querySelector('.account-panel')?.remove();
  const shell = (html) => { close(); const b=document.createElement('button'); b.className='account-modal-backdrop'; b.setAttribute('aria-label','Close'); b.onclick=close; const p=document.createElement('section'); p.className='account-panel'; p.innerHTML=html; document.body.append(b,p); return p; };
  const login = () => { const p=shell(`<div class="auth-logo">NEXORA <em>MINUTES</em></div><h2>Welcome back 👋</h2><p>Fast groceries, delivered to your doorstep.</p><div class="phone-row"><div class="country-code">🇧🇩 +880</div><input class="auth-input" id="nm-phone" inputmode="tel" maxlength="11" placeholder="1XXXXXXXXX"></div><button class="auth-primary" id="nm-continue">Continue with OTP →</button><button class="auth-secondary" id="nm-guest">Continue as Guest</button><p class="security-note">🔒 Your number is safe with us.</p>`); p.querySelector('#nm-continue').onclick=()=>{ const phone=p.querySelector('#nm-phone').value.replace(/\D/g,''); if(phone.length<10){ const e=document.createElement('p'); e.className='auth-error'; e.textContent='Please enter a valid mobile number.'; p.querySelector('.phone-row').after(e); return; } otp(phone); }; p.querySelector('#nm-guest').onclick=()=>{ setUser({name:'Guest',phone:''}); account(); }; };
  const otp = (phone) => { let left=30; const p=shell(`<div class="auth-logo">NEXORA <em>MINUTES</em></div><h2>Verify your number</h2><p>Enter the 6-digit OTP sent to +880 ${phone}</p><div class="otp-row">${[0,1,2,3,4,5].map(i=>`<input class="otp-input" maxlength="1" inputmode="numeric" data-i="${i}">`).join('')}</div><button class="auth-primary" id="nm-verify">Verify & Continue</button><button class="auth-secondary change-number" id="nm-change">Change mobile number</button><p class="security-note" id="nm-timer">Resend OTP in 00:30</p>`); const inputs=[...p.querySelectorAll('.otp-input')]; inputs.forEach((x,i)=>x.oninput=()=>{x.value=x.value.replace(/\D/g,'');if(x.value&&inputs[i+1])inputs[i+1].focus();}); p.querySelector('#nm-change').onclick=login; p.querySelector('#nm-verify').onclick=()=>{setUser({name:'Customer',phone:'+880 '+phone});account();}; const timer=p.querySelector('#nm-timer'); const t=setInterval(()=>{left--; if(!document.body.contains(timer)){clearInterval(t);return;} timer.textContent=left>0?`Resend OTP in 00:${String(left).padStart(2,'0')}`:'Resend OTP'; if(left<=0)clearInterval(t);},1000); };
  const account = () => { const u=getUser() || {name:'Customer',phone:''}; const os=orders(); const p=shell(`<div class="account-header"><div><div class="auth-logo">NEXORA <em>MINUTES</em></div><h2>Hello, ${u.name} 👋</h2></div><button class="drawer-close" id="nm-close">×</button></div><div class="profile-card"><div class="profile-line">📱 <b>Mobile Number</b><span>${u.phone||'Not added'}</span></div><div class="profile-line">📍 <b>Delivery Address</b><span>${u.address||'Add an address at checkout'}</span></div><button class="profile-edit" id="nm-edit">✏️ Edit Profile</button></div><div class="account-menu"><button>📦 My Orders <span>›</span></button><button>🔄 Order Again <span>›</span></button><button>❤️ Wishlist <span>›</span></button><button>📍 Saved Addresses <span>›</span></button><button>💳 Payment Methods <span>›</span></button><button>🎁 Offers & Rewards <span>›</span></button><button>⚙️ Settings <span>›</span></button><button id="nm-logout">🚪 Logout <span>›</span></button></div><h3 class="orders-title">My Orders</h3>${os.length?os.map(o=>`<div class="order-card"><div class="order-top"><b>${o.id}</b><span class="status">${o.status||'Confirmed'}</span></div><div>${new Date(o.createdAt||Date.now()).toLocaleDateString()} · Order amount</div><div class="order-amount">৳${o.total}</div><button class="view-order">View Details →</button></div>`).join(''):'<p>No recent orders yet. Your completed orders will appear here.</p>'}`); p.querySelector('#nm-close').onclick=close; p.querySelector('#nm-logout').onclick=()=>{localStorage.removeItem('nexora-user');login();}; p.querySelector('#nm-edit').onclick=()=>editProfile(u); };
  const editProfile=(u)=>{const p=shell(`<div class="auth-logo">NEXORA <em>MINUTES</em></div><h2>Edit Profile</h2><p>Keep your account details up to date.</p><label>Name<input class="auth-input" id="nm-name" value="${u.name||''}"></label><label>Mobile Number<input class="auth-input" id="nm-phone-edit" value="${u.phone||''}" readonly></label><label>Delivery Address<input class="auth-input" id="nm-address" value="${u.address||''}" placeholder="Village / road / house"></label><button class="auth-primary" id="nm-save">Save Changes</button>`); p.querySelector('#nm-save').onclick=()=>{setUser({...u,name:p.querySelector('#nm-name').value.trim()||'Customer',address:p.querySelector('#nm-address').value.trim()});account();}; };
  const open = () => getUser() ? account() : login();
  document.addEventListener('click',e=>{const a=e.target.closest('.account-btn,.bottom-nav a[href="#account"]');if(a){e.preventDefault();open();}});
})();